font_family IosevkaTerm Nerd Font
font_size 18

shell_integration disabled

cursor_shape block

remember_window_size no
inital_window_width 78c
inital_window_height 23c
window_padding_width 28
cursor_blink_interval 0

background_opacity 0.95
confirm_os_window_close 0

sync_to_monitor no

cursor_trail 2


# BEGIN_KITTY_THEME
# Base16-Gruvbox-Dark-Hard
include current-theme.conf
# END_KITTY_THEME
