font_family IosevkaTerm Nerd Font Mono
font_size 18

disable_ligatures no
enable_audio_bell no

shell_integration disabled

cursor_shape block

remember_window_size no
inital_window_width 78c
inital_window_height 23c
#window_padding_width 20
window_padding_width 40
cursor_blink_interval 0

background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0

#repaint_delay 8
#input_delay 0
sync_to_monitor yes

cursor_trail 1

# BEGIN_KITTY_THEME
# Base16-Gruvbox-Dark-Hard
include current-theme.conf
# END_KITTY_THEME
