# Arreglar los colores
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

# Redefinir la tecla lider
unbind C-b
set -g prefix C-g
bind-key C-g send-prefix

# Unbind de las teclas para abrir paneles
unbind %
unbind '"'

# Asignar binds para abrir paneles
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Vim-movement sin prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Empezar numeración desde el 1 (en general)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Cambiar entre diferentes tabs con Alt+number
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Vim-movement para copiar
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Customize bar

## General
set -g status "on"
set-option -g status-position top

## Windows
set -g status-style bg=default
set -g status-justify absolute-centre
set -g window-status-activity-style ""
set-window-option -g window-status-current-style bold

## Status-bar-right
set -g status-right ""

## Status-bar-right
set -g status-left "#S"

# Script for sessions
unbind n
unbind p
bind f run-shell "tmux neww ~/scripts/tmux-sessions.sh"
bind D run-shell "tmux neww ~/scripts/tmux-sessions.sh ~/.config"
bind h run-shell "tmux neww ~/scripts/tmux-sessions.sh ~"
bind S run-shell "tmux neww ~/scripts/tmux-sessions.sh ~/scripts"
bind n run-shell "tmux neww ~/scripts/tmux-sessions.sh ~/privrepo"

bind p run-shell "tmux neww ~/scripts/open-pdf.sh"

# For launch other scritps
unbind s
bind s run-shell "tmux neww ~/scripts/fzf-scripts.sh"

# Matar la sesión de tmux
unbind d

# Floating window
bind -n C-t if-shell -F '#{==:#{session_name},float}' {
detach-client
} {
display-popup -w 80% -h 80% -E "tmux new-session -A -s float "
}

#bind -n C-f display-popup -d "${pane_current_path}" -w 80% -h 80% -E

# Vim-movement para los paneles
#bind h select-pane -L
#bind j select-pane -D
#bind k select-pane -U
#bind l select-pane -R

