###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = yazi
$menu = pkill rofi || sh ~/.config/rofi/launchers/colorful/launcher.sh
$browser = zen-browser
$dmenu = pkill rofi || sh ~/.config/colorschemes/launcher.sh
