##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.1

layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.1


# PUTTY
#windowrule {
#    name = putty
#    match:class = ^(putty)$
#    float = on
#    size = (monitor_w*0.8) (monitor_h*0.8)
#    center = on
#    opacity = 1.0 0.8
#    no_blur = on
#    workspace = special:magic
#}

# WK ALT + S GNS3
workspace = special:magic, gapsout:50, gapsin:7

windowrule {
    name = GNS3
    match:class = ^(gns3)$
    #size = (monitor_w*0.95) (monitor_h*0.95)
    #size = (window_w*0.95) (window_h*0.95)
    #center = on
    workspace = special:magic
    animation = popin
}

# WK ALT + O OBSIDIAN
workspace = special:obsidian, gapsout:50, gapsin:7

windowrule {
    name = obsidain
    match:class = ^(obsidian)$
    #size = (monitor_w*0.95) (monitor_h*0.95)
    #size = (window_w*0.95) (window_h*0.95)
    #center = on
    workspace = special:obsidian
    animation = popin
}


windowrule {
    name = file picker in browser
    match:class = xdg-desktop-portal-gtk
    float = on
    center = on
    size = (window_w*0.7) (window_h*0.7)
}

# VMs float in GNS3
windowrule {
    name = floating VMs in GNS3
    match:class = Vncviewer
    float = on
    center = on
}

# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule {
#     name = no-gaps-wtv1
#     match:float = false
#     match:workspace = w[tv1]
#
#     border_size = 0
#     rounding = 0
# }
#
# windowrule {
#     name = no-gaps-f1
#     match:float = false
#     match:workspace = f[1]
#
#     border_size = 0
#     rounding = 0
# }
